import Head from "next/head";
import Link from "next/link";
import {
  Header,
  Brand,
  HotCategory,
  GridProducts,
  Banner,
  NewsLetter,
} from "../components";

export default function Home() {
  return (
    <div>
      <Head>
        <title>ShopAnnie</title>
        <meta name="description" content="Generated by DevKeo" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <Brand />
        <HotCategory />
        <GridProducts />
        <Banner />
        <NewsLetter />
        <p>
          <Link href="/products/product">Go to product page</Link>
        </p>
      </main>
    </div>
  );
}
